matrix:
- name: README
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
    comments: false
    ignores:
    - code
    - pre
  - pyspelling.filters.url:
  sources:
  - 'README.md'
  default_encoding: utf-8
- name: HTML
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.html:
    comments: false
    ignores:
    - code
    - pre
  - pyspelling.filters.url:
  sources:
  - 'build/docs/**/*.html'
  default_encoding: utf-8
