# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
default: true
# The snippets includes typically do not start with the h1 heading level. Therefore disabling this check
MD041: false
