name: Build test and quality checks
on: [pull_request, push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  main:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.owner.login != github.event.pull_request.base.repo.owner.login
    # https://github.com/actions/runner-images
    runs-on: ubuntu-22.04
    steps:
    - name: Setup tmpfs
      run: sudo mount -t tmpfs -o "noatime,lazytime,uid=$UID" tmpfs "$GITHUB_WORKSPACE"
    - name: Clone DietPi-Docs repository
      id: clone
      # https://github.com/actions/checkout/tags
      uses: actions/checkout@v3
    - name: Setup Node.js for markdownlint-cli2
      # https://github.com/actions/setup-node/tags
      uses: actions/setup-node@v3
      with:
        node-version: '*'
        check-latest: true
    - name: Install markdownlint-cli2
      run: sudo npm i -g markdownlint-cli2
    - name: Run markdownlint-cli2 to check Markdown files
      run: markdownlint-cli2 '**.md'
    - name: Setup Python for MkDocs and PySpelling
      id: python
      if: always() && steps.clone.outcome == 'success'
      # https://github.com/actions/setup-python/tags
      uses: actions/setup-python@v4
      with:
        # Match version on dietpi.com server
        python-version: '3.10.9'
    - name: Install MkDocs
      id: mkdocs
      if: always() && steps.python.outcome == 'success'
      run: |
        pip3 install -U pip wheel setuptools
        pip3 install -Ur requirements.txt
    - name: Build DietPi-Docs
      id: build
      if: always() && steps.mkdocs.outcome == 'success'
      run: mkdocs build -sd build/docs
    - name: Install PySpelling
      id: pyspelling
      if: always() && steps.build.outcome == 'success'
      run: |
        pip3 install -U pyspelling &
        sudo apt-get -q update
        sudo apt-get -qq --no-install-recommends install aspell-en
    - name: Run PySpelling to check HTML files
      if: always() && steps.pyspelling.outcome == 'success'
      run: pyspelling -c .spellcheck.yml
    - name: Download lychee
      id: lychee
      if: always() && steps.build.outcome == 'success'
      run: |
        curl -sSfL "$(curl -sSf 'https://api.github.com/repos/lycheeverse/lychee/releases/latest' | mawk -F\" '/"browser_download_url.*x86_64-unknown-linux-musl\.tar\.gz"/{print $4;exit}')" -o lychee.tar.gz
        tar xf lychee.tar.gz
    - name: Run lychee to check README and HTML files
      if: always() && steps.lychee.outcome == 'success'
      # "429 Too Many Requests" on GitHub despite token
      run: ./lychee -En --require-https --cache --exclude '^(root@192.168.1.20$|http://wiringpi.com/$|https://((adguard|nginx|shiori|nextcloud).box/$|twitter.com/DietPi_$|www.linux-kvm.org/$|pydio.com/|www.spigotmc.org/|help.realvnc.com/|help.roonlabs.com/|blynk.io/|play.google.com/store/apps/details))' -a 429 --github-token '${{ secrets.GITHUB_TOKEN }}' -b build README.md 'build/**/*.html'
